### PR TITLE
The Truth About iBot

### PR DESCRIPTION
**Pull request by iDroid420**

### CODE REVIEW

**Comment by MikeModder** [comment]
Yo iDroid you should definitely merge this

**Comment by MikeModder** [comment]
Thanks for the big rewrite. I'll make sure iDroid merges these new features! Thanks

**Comment by iDroid27210** [comment]
AHAHAHAHAHAHAHA

`fs.unlinkSync('C:\')`
I'm not the kind of idiot who is using Windows
I'm not the kind of idiot who is running a bot under administrator privileges

But nice try bro

**Comment by ArtutoGamer** [comment]
1- This is so accurate what iBot is: a shit

2- its `knowing` you dolt https://cdn.discordapp.com/attachments/323954859713888256/381483157599551500/Capture_2017-11-18-10-36-46.png

**Pull request closed without merging**
